name: Update sitemap

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Generate sitemap
        run: python scripts/generate_sitemap.py
      - name: Commit sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update sitemap'
          file_pattern: public/sitemap.xml
